/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frame;

import java.awt.Color;

/**
 *
 * @author GIA HUY
 */
public class TagEditButton extends javax.swing.JPanel {

    private String displayTag;
    private boolean isInList;

    /**
     * Creates new form TagEditButton
     */
    public TagEditButton() {
        initComponents();
    }

    public TagEditButton(String displayTag, boolean isInList) {
        initComponents();
        this.displayTag = displayTag;
        this.isInList = isInList;
        tagName.setText(displayTag);
    }

    public void updateState() {
        if (isInList){
            changeToMinusState();
            isInList = false;
        }else{
            changeToAddState();
            isInList = true;
        }
    }

    private void changeToAddState() {
        actionButton.setText("+");
        actionButton.setForeground(Color.GREEN);
    }

    private void changeToMinusState() {
        actionButton.setText("-");
        actionButton.setForeground(Color.RED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tagName = new javax.swing.JLabel();
        actionButton = new javax.swing.JButton();

        tagName.setBackground(new java.awt.Color(255, 255, 255));
        tagName.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tagName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tagName.setText("tag");
        tagName.setPreferredSize(new java.awt.Dimension(200, 60));
        add(tagName);

        actionButton.setBackground(new java.awt.Color(242, 242, 242));
        actionButton.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        actionButton.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        actionButton.setText("+");
        actionButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        actionButton.setMaximumSize(new java.awt.Dimension(65, 65));
        actionButton.setMinimumSize(new java.awt.Dimension(65, 65));
        actionButton.setPreferredSize(new java.awt.Dimension(65, 65));
        add(actionButton);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionButton;
    private javax.swing.JLabel tagName;
    // End of variables declaration//GEN-END:variables
}
