/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Frame;

import imagemanager.Manager;
import imagemanager.Tag;
import imagemanager.TagManager;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class TagManagerMenu extends javax.swing.JDialog {
    private TagManager tagManager = TagManager.getInstance();
    private TagTableModel model = new TagTableModel(tagManager.getMap());

    /**
     * Creates new form TagManagerMenu
     */
    public TagManagerMenu(java.awt.Frame parent, boolean modal, TagManager tagManager) {
        super(parent, modal);
        initComponents();
        this.tagManager = tagManager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tagTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        addButton.setText("Add Tag");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton);

        deleteButton.setText("Delete Tag");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.CardLayout());

        tagTable.setModel(model);
        tagTable.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(tagTable);
        tagTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tagTable.setCellSelectionEnabled(false);
        tagTable.setRowSelectionAllowed(true);

        jPanel2.add(jScrollPane2, "card2");

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        Tag newTag = new Tag(JOptionPane.showInputDialog("Add new tag:"));
        if (tagManager.add(newTag) == false){
            JOptionPane.showMessageDialog(null, "Tag already exist","Warning",JOptionPane.WARNING_MESSAGE);
        }
        refresh();
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int rowIndex = tagTable.convertRowIndexToModel(tagTable.getSelectedRow());
        model.removeRow(rowIndex);
    }//GEN-LAST:event_deleteButtonActionPerformed

    public void refresh(){
        model.fireTableDataChanged();
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tagTable;
    // End of variables declaration//GEN-END:variables
}
